name: Test PyRES Installation

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-installation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        method: [pip, conda]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Miniconda
        if: matrix.method == 'conda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      
      # Create conda environment and install dependencies
      - name: Create virtual environment (MacOS/Linux - conda)
        if: ${{ (matrix.method == 'conda') && (runner.os != 'Windows') }}
        shell: bash -l {0}
        run: bash bootstrap.sh

      - name: Create virtual environment (Windows - conda)
        if: ${{ (matrix.method == 'conda') && (runner.os == 'Windows') }}
        shell: cmd.exe -l {0}
        run: call .\bootstrap.bat
      
      # Create pip environment and install dependencies
      - name: Create virtual environment (MacOS/Linux - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os != 'Windows') }}
        shell: bash -l {0}
        run: bash bootstrap.sh no-conda

      - name: Create virtual environment (Windows - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os == 'Windows') }}
        shell: cmd.exe -l {0}
        run: call .\bootstrap.bat