name: Test PyRES Installation

on:
  push:
  pull_request:

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        method: [pip, conda]
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Miniconda
        if: matrix.method == 'conda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment (MacOS/Linux - conda)
        if: ${{ (matrix.method == 'conda') && (runner.os != 'Windows') }}
        shell: bash -l {0}
        run: bash bootstrap.sh

      - name: Create virtual environment (Windows - conda)
        if: ${{ (matrix.method == 'conda') && (runner.os == 'Windows') }}
        shell: cmd.exe {0}
        run: conda env create -f environment.yml

      - name: Create virtual environment environment (MacOS/Linux - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os != 'Windows') }}
        shell: bash -l {0}
        run: bash bootstrap.sh no-conda

      - name: Create virtual environment (Windows - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os == 'Windows') }}
        shell: cmd.exe {0}
        run: call .\bootstrap.bat

      - name: Run test example (conda)
        if: matrix.method == 'conda'
        shell: bash -l {0}
        run: |
          conda activate pyres-env
          python examples/E1_virtual-room.py

      - name: Run test example (MacOS/Linux - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os != 'Windows') }}
        shell: bash -l {0}
        run: |
          source pyres-env/bin/activate
          python examples/E1_virtual-room.py

      - name: Run test example (Windows - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os == 'Windows') }}
        shell: cmd.exe {0}
        run: |
          call .\pyres-env\Scripts\activate.bat
          python examples/E1_virtual-room.py