name: Test PyRES Installation

on:
  push:
  pull_request:

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-14]
        method: [conda, pip]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install Miniconda
        if: matrix.method == 'conda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10

      - name: Create and activate environment (conda)
        if: matrix.method == 'conda'
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml
          conda activate pyres-env
          python -m pip install --upgrade pip

      - name: Create and activate environment (pip)
        if: matrix.method == 'pip'
        run: |
          python -m venv pyres-env
          source pyres-env/bin/activate || .\pyres-env\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test example
        shell: bash -l {0}
        run: |
          source pyres-env/bin/activate || .\pyres-env\Scripts\activate
          python examples/E1_virtual-room.py