name: Test PyRES Installation

on:
  push:
  pull_request:

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        method: [conda, pip]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Miniconda (only if conda)
        if: matrix.method == 'conda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
          environment-file: environment.yml
          activate-environment: pyres-env

      - name: Install additional pip dependencies (only if conda)
        if: matrix.method == 'conda'
        run: |
          pip install flamo pyfar pyrato seaborn matplotlib pyqt5

      - name: Set up venv and install pip dependencies (only if pip)
        if: matrix.method == 'pip'
        run: |
          python -m venv pyres-env
          . pyres-env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test example
        run: |
          . pyres-env/bin/activate
          python examples/E1_virtual-room.py