name: Test PyRES Installation

on:
  push:
  pull_request:

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        method: [pip]
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Miniconda
        if: matrix.method == 'conda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment environment (conda)
        if: matrix.method == 'conda'
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml

      # - name: Create and activate environment (MacOS - pip)
      #   if: ${{ (matrix.method == 'pip') && (runner.os == 'macOS') }}
      #   run: |
      #     brew install libsndfile
      #     python -m venv pyres-env
      #     source pyres-env/bin/activate
      #     echo "export DYLD_LIBRARY_PATH=$(brew --prefix libsndfile)/lib:$DYLD_LIBRARY_PATH" >> pyres-env/bin/activate
      #     python -m pip install --upgrade pip setuptools wheel
      #     pip install -r requirements.txt

      # - name: Create and activate environment (Linux - pip)
      #   if: ${{ (matrix.method == 'pip') && (runner.os == 'Linux') }}
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y libsndfile1
      #     python -m venv pyres-env
      #     source pyres-env/bin/activate
      #     python -m pip install --upgrade pip setuptools wheel
      #     pip install -r requirements.txt

      # - name: Create and activate environment (Windows - pip)
      #   if: ${{ (matrix.method == 'pip') && (runner.os == 'Windows') }}
      #   run: |
      #     python -m venv pyres-env
      #     .\pyres-env\Scripts\activate.bat
      #     python -m pip install --upgrade pip setuptools wheel
      #     pip install -r requirements.txt

      - name: Create virtual environment environment (MacOS/linux - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os != 'Windows') }}
        shell: bash -l {0}
        run: bash bootstrap.sh no-conda

      - name: Create virtual environment (Windows - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os == 'Windows') }}
        shell: cmd.exe {0}
        run: .\bootstrap.bat

      - name: Run test example (conda)
        if: matrix.method == 'conda'
        shell: bash -l {0}
        run: |
          conda activate pyres-env
          python examples/E1_virtual-room.py

      - name: Run test example (MacOS/Linux - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os != 'Windows') }}
        shell: bash -l {0}
        run: |
          source pyres-env/bin/activate
          python examples/E1_virtual-room.py

      - name: Run test example (Windows - pip)
        if: ${{ (matrix.method == 'pip') && (runner.os == 'Windows') }}
        shell: cmd.exe {0}
        run: |
          .\pyres-env\Scripts\activate.bat
          python examples/E1_virtual-room.py